name: attendance-time-check

on:
  # Set your own working time!
  schedule:
    - cron: '15 1,11 * * 1-5'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google.list
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Chrome Driver
        run: |
          # CHROME_VERSION_PATH=LATEST_RELEASE_$(google-chrome --version | cut -d " " -f 3 | cut -d "." -f 1-3)
          # CHROME_DRIVER_VERSION_PATH=$(wget -qO- "https://chromedriver.storage.googleapis.com/${CHROME_VERSION_PATH}")
          # CHROME_DRIVER_LOCATION_PATH="https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION_PATH/chromedriver_linux64.zip"
          CHROME_DRIVER_LOCATION_PATH="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip"
          sudo mkdir /chromedriver
          wget -O chromedriver_linux64.zip $CHROME_DRIVER_LOCATION_PATH
          unzip chromedriver_linux64.zip
          echo "/chromedriver" >> $GITHUB_PATH

      - name: add-mask-for-secrets-for-KOT-and-Slack
        run: |
          echo "::add-mask::${{ secrets.KING_OF_TIME_LOGIN_ID }}"
          echo "::add-mask::${{ secrets.KING_OF_TIME_LOGIN_PASSWORD }}"
          echo "::add-mask::${{ secrets.SLACK_INCOMING_WEB_HOOK_URL }}"

      - name: Execute attendance-checker-for-king-of-time script
        env:
          LANG: 'ja_JP.UTF-8'
          LANGUAGE: 'ja_JP:jp'
          TZ: 'Asia/Tokyo'
          # these env are needed, so please set these env in your fork repository.
          KING_OF_TIME_LOGIN_ID: ${{ secrets.KING_OF_TIME_LOGIN_ID }}
          KING_OF_TIME_LOGIN_PASSWORD: ${{ secrets.KING_OF_TIME_LOGIN_PASSWORD }}
          OPENING_HOUR: ${{ secrets.OPENING_HOUR }}
          CLOSING_HOUR: ${{ secrets.CLOSING_HOUR }}
          SLACK_INCOMING_WEB_HOOK_URL: ${{ secrets.SLACK_INCOMING_WEB_HOOK_URL }}
        run: |
          yarn add attendance-checker-for-king-of-time@^1
          node -e "require('attendance-checker-for-king-of-time')"
